### ISSUE TITLE
Vehicle-Workshop interaction and vehicle-world bounds check needs re-implementing

### ISSUE THREAD

**Issue by MindokRuvaak** [sophucking/Grupp16Labb3#1]
After removing "VisualItem" form the simulation class the vehicles no longer have a ''size'' property which was used for collision and world-boundary checks. 

Decorator for vehicle size in VehicleSimulation which is given to VisualItem? 
-> VisualItem has a ''Sized-Vehicle/-Workshop'' instead?

**Comment by Jourmumriken** [comment]
On it

**Comment by Jourmumriken** [comment]
solving this issue creates other issues. See new issue#2 that i created
