### ISSUE TITLE
Circular dependency between VehicleView and VehicleSimulation

### ISSUE THREAD

**Issue by Jourmumriken** [sophucking/Grupp16Labb3#2]
Due to the observer pattern we need VehicleView to have a VehicleSimulation but since VehicleSimulation acts as both application and model this creates a circular dependecy.

Solution: Implement a proper Application

**Comment by MindokRuvaak** [comment]
Removed view dependency on simulation, the x and y coordinates of VisualItem - objects instead return the coordinates of the contained vehicle/workshop.
The graphical representation and the object it represents should now always be in sync with regards to their position in the world.

**Comment by MindokRuvaak** [comment]
Note: implementation is on ''testNewViewUpdate'' branch and not yet merged in case we want to use a different solution.
