### ISSUE TITLE
Controller handles movement still!

### ISSUE THREAD

**Issue by Jourmumriken** [sophucking/Grupp16Labb3#3]
Since controller still handles car movement (its a mutator of vehicles, very bad!) we need to do some spagetti to get vehicleSimlation to check for a boundry collission and then turn the car back around with controller. 

Solution: Move all this logic into VehicleSimulation

**Comment by Jourmumriken** [comment]
I take this back we can "bounce" cars in the simulation. However there is still some of this left in controller (move() for example) so the issue is still rellevant

**Comment by MindokRuvaak** [comment]
Fixed.
Removed the update and moveCar methods in controller, since they are not connected to any user inputs (and thus not the responsibility of the controller), the move method is instead called inside simulation's update method for each vehicle each tick.
