### ISSUE TITLE
Volvo240 Bounces randomly off nothing

### ISSUE THREAD

**Issue by Jourmumriken** [sophucking/Grupp16Labb3#4]
randomly while running the Volvo240 will choose a new spot to bounce off as if it was a wall. Only the 240 does this for me. It seems to happen always.

No clue why, look into it!

**Comment by MindokRuvaak** [comment]
Looking into it now

**Comment by MindokRuvaak** [comment]
Fixed, remember seeing this before for some reason the boundary check is funky if the world size is exactly same as window size but if the world is one pixel larger in the problematic direction it's fine.

Added one pixel in each direction for symmetry.
